### ISSUE TITLE
[2.67.1-pre] Prod Glitch Deploy: PostProcessingHandler.ts(91,45): error TS2345: Argument of type 'void | Pass | Effect' is not assignable to parameter of type 'Pass | Effect'.

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#136]
### Describe the bug 💬

Using this issue https://github.com/needle-tools/needle-engine-support/issues/135#issue-1642415419

I Build & Deploy: Prod to Glitch using Deploy to Glitch and get these blocking errors since updating from 2.66.1-pre to 2..67.1-pre

```
../../Library/PackageCache/com.needle.engine@2.67.1-pre/package~/src/engine-components/postprocessing/PostProcessingHandler.ts(91,45): error TS2345: Argument of type 'void | Pass | Effect' is not assignable to parameter of type 'Pass | Effect'.
Open C:\Unity_Projects\NeedleARDemo\Needle\ARDemo/../../Library/PackageCache/com.needle.engine@2.67.1-pre/package~/src/engine-components/postprocessing/PostProcessingHandler.ts

```
and
```
../../Library/PackageCache/com.needle.engine@2.67.1-pre/package~/src/engine/engine_patcher.ts(86,9): error TS7030: Not all code paths return a value.
Open C:\Unity_Projects\NeedleARDemo\Needle\ARDemo/../../Library/PackageCache/com.needle.engine@2.67.1-pre/package~/src/engine/engine_patcher.ts

```

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

2..67.1-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "C:/Unity_Projects/NeedleARDemo/Assets",
  "UnityVersion": "2022.2.12f1",
  "SceneName": "ARDemo",
  "ProjectPath": "Needle/ARDemo",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v18.15.0",
  "NpmVersion": "9.6.2",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "UniversalRenderPipelineAsset (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.67.1-pre",
  "NeedleEngineVersion": "2.67.1-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 2 = 0.5 mb\r\n•\t<b>Total = 0.5 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 2 = 0.5 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.Components.WebARSessionRoot",
    "Needle.Engine.Components.TeleportTarget",
    "Needle.Engine.Components.ObjectRaycaster",
    "Needle.Engine.AdditionalData.LightShadowData",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.WebXRSync",
    "Needle.Typescript.GeneratedComponents.WebXRInterface",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.AdditionalData.CameraARData",
    "Needle.Typescript.GeneratedComponents.AlignHeightToGround",
    "Needle.Typescript.GeneratedComponents.ARControls",
    "Needle.Typescript.GeneratedComponents.IsGround"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1. Load up project scenes > ARDemo
2. Try to deploy to glitch as Prod using Export Info > Deploy to Glitch component in scene
3. See errors
```

### Reproduction ♻

[Bugreport-ARDemo-230328-113648_uw.zip](https://github.com/needle-tools/needle-engine-support/files/11088314/Bugreport-ARDemo-230328-113648_uw.zip)

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
The same doesnt seem to happen when doing a normal dev/prod build - can you verify that?

**Comment by marwie** [comment]
What if you change the script from
``"build:dev": "tsc && vite build && npm run copy-files"``
to
``"build:dev": "vite build && npm run copy-files"``

**Comment by ROBYER1** [comment]
> What if you change the script from `"build:dev": "tsc && vite build && npm run copy-files"` to `"build:dev": "vite build && npm run copy-files"`

That fixed it, is there a way to automate fixing that on package update/install of Needle after update? I assume this would affect various other projects I try to update to this version on where the package.json of the project is invalid

**Comment by marwie** [comment]
Sould be fixed in 2.67.2-pre
